apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pdp52m64l-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/pdp52m64l-java-springboot-gitops